"""CLIから呼び出す最上位の制御処理。"""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from pathlib import Path

from dotenv import load_dotenv

from business_analysis_agents.agents.scenario import (
    MissingOpenAIAPIKeyError as ScenarioMissingOpenAIAPIKeyError,
    run_scenario_agent,
    save_scenario_output,
)
from business_analysis_agents.agents.data_rule import (
    MissingOpenAIAPIKeyError as DataRuleMissingOpenAIAPIKeyError,
)
from business_analysis_agents.agents.workflow import (
    MissingOpenAIAPIKeyError as WorkflowMissingOpenAIAPIKeyError,
)
from business_analysis_agents.config import load_config_from_env
from business_analysis_agents.data_rule_pipeline import run_data_rule_pipeline
from business_analysis_agents.fixed_resources import (
    DEFAULT_DATA_ONTOLOGY,
    DEFAULT_RULE_ONTOLOGY,
    DEFAULT_SCENARIO_ONTOLOGY,
    DEFAULT_WORKFLOW_ONTOLOGY,
    load_fixed_turtle,
)
from business_analysis_agents.document_loader import load_pdf_document
from business_analysis_agents.models import ScenarioAgentInput
from business_analysis_agents.workflow_pipeline import run_workflow_pipeline


def build_parser() -> argparse.ArgumentParser:
    """CLI引数パーサーを作成する。"""

    parser = argparse.ArgumentParser(
        description="業務文書PDFから固定Ontology準拠のScenario RDFを生成します。"
    )
    parser.add_argument(
        "pdf_path",
        nargs="?",
        help="業務文書PDFのパス。未指定の場合は起動確認メッセージだけを表示します。",
    )
    return parser


def build_workflow_parser() -> argparse.ArgumentParser:
    """Create the workflow subcommand parser."""

    workflow_parser = argparse.ArgumentParser(
        prog="python -m business_analysis_agents workflow",
        description="Generate Workflow RDF from Scenario RDF and a PDF.",
    )
    workflow_parser.add_argument(
        "--scenario",
        required=True,
        help="Path to scenario_final.ttl generated by the Scenario Agent.",
    )
    workflow_parser.add_argument(
        "--pdf",
        required=True,
        help="Path to the original business document PDF.",
    )
    workflow_parser.add_argument(
        "--output-dir",
        default="outputs/workflow",
        help="Directory for Workflow RDF artifacts.",
    )
    workflow_parser.add_argument(
        "--ontology",
        default=str(DEFAULT_WORKFLOW_ONTOLOGY),
        help="Workflow ontology Turtle file.",
    )
    workflow_parser.add_argument(
        "--max-workflow-iterations",
        type=int,
        default=3,
        help="Maximum Workflow RDF revision retries.",
    )
    workflow_parser.add_argument(
        "--save-debug-outputs",
        action="store_true",
        help="Save ontology, SHACL, agent output, and run metadata artifacts.",
    )
    return workflow_parser


def build_data_rule_parser() -> argparse.ArgumentParser:
    """Create the data-rule subcommand parser."""

    parser = argparse.ArgumentParser(
        prog="python -m business_analysis_agents data-rule",
        description="Generate Data RDF and Rule RDF from Scenario RDF and a PDF.",
    )
    parser.add_argument(
        "--scenario",
        required=True,
        help="Path to scenario_final.ttl generated by the Scenario Agent.",
    )
    parser.add_argument(
        "--pdf",
        required=True,
        help="Path to the original business document PDF.",
    )
    parser.add_argument(
        "--output-dir",
        default="outputs/data_rule",
        help="Directory for Data RDF and Rule RDF artifacts.",
    )
    parser.add_argument(
        "--data-ontology",
        default=str(DEFAULT_DATA_ONTOLOGY),
        help="Data ontology Turtle file.",
    )
    parser.add_argument(
        "--rule-ontology",
        default=str(DEFAULT_RULE_ONTOLOGY),
        help="Rule ontology Turtle file.",
    )
    parser.add_argument(
        "--max-data-iterations",
        type=int,
        default=3,
        help="Maximum Data RDF revision retries.",
    )
    parser.add_argument(
        "--max-rule-iterations",
        type=int,
        default=3,
        help="Maximum Rule RDF revision retries.",
    )
    return parser


def run(argv: Sequence[str] | None = None) -> int:
    """プロトタイプを起動し、必要に応じてPDFからシナリオを生成する。"""

    raw_args = list(argv) if argv is not None else []
    load_dotenv()
    config = load_config_from_env()

    if raw_args[:1] == ["workflow"]:
        args = build_workflow_parser().parse_args(raw_args[1:])
        try:
            result = run_workflow_pipeline(
                scenario_file=args.scenario,
                model=config.openai_model,
                pdf_file=args.pdf,
                output_dir=args.output_dir,
                max_workflow_iterations=args.max_workflow_iterations,
                ontology_file=args.ontology,
                save_debug_outputs=args.save_debug_outputs,
            )
        except WorkflowMissingOpenAIAPIKeyError as error:
            print(f"エラー: {error}")
            return 1
        except (FileNotFoundError, PermissionError, ValueError) as error:
            print(f"エラー: {error}")
            return 1
        print("Workflow RDF生成を完了しました")
        print(f"出力先: {result['output_dir']}")
        print(f"最終状態: {result['final_status']}")
        return 0

    if raw_args[:1] == ["data-rule"]:
        args = build_data_rule_parser().parse_args(raw_args[1:])
        try:
            result = run_data_rule_pipeline(
                scenario_file=args.scenario,
                model=config.openai_model,
                pdf_file=args.pdf,
                output_dir=args.output_dir,
                max_data_iterations=args.max_data_iterations,
                max_rule_iterations=args.max_rule_iterations,
                data_ontology_file=args.data_ontology,
                rule_ontology_file=args.rule_ontology,
            )
        except DataRuleMissingOpenAIAPIKeyError as error:
            print(f"エラー: {error}")
            return 1
        except (FileNotFoundError, PermissionError, ValueError) as error:
            print(f"エラー: {error}")
            return 1
        print("Data RDF / Rule RDF生成を完了しました")
        print(f"出力先: {result['output_dir']}")
        print(f"最終状態: {result['final_status']}")
        return 0

    args = build_parser().parse_args(raw_args)
    if not args.pdf_path:
        print("システムを開始しました")
        return 0

    try:
        document = load_pdf_document(args.pdf_path)
        _, scenario_ontology = load_fixed_turtle(
            DEFAULT_SCENARIO_ONTOLOGY,
            "Scenario ontology",
        )
        output = run_scenario_agent(
            ScenarioAgentInput(
                document=document,
                ontology_turtle=scenario_ontology,
            ),
            model=config.openai_model,
        )
    except ScenarioMissingOpenAIAPIKeyError as error:
        print(f"エラー: {error}")
        return 1
    except (FileNotFoundError, PermissionError, ValueError) as error:
        print(f"エラー: {error}")
        return 1

    scenario_path = save_scenario_output(
        output,
        Path(config.output_dir) / "scenario",
    )
    print("システムを開始しました")
    print(f"シナリオを保存しました: {scenario_path}")
    return 0
